### ISSUE TITLE
Buy plants for office

### ISSUE THREAD

**Issue by ericforward** [Forward-architects/Forward-Office-Development#4]

**Comment by 123betta** [comment]
@ericforward  you can go on piscopo gardens website and choose the plants you want and then let me know the names and heights (approx) and I will get a quote for plants together with high-up. Then will take a decision. Can we have a deadline on this please in case anyone would like to comments. Deadline: Fri 28th April.

Thanks
B

**Comment by ericforward** [comment]
@katrinagauci do you want to help me out with this?

**Comment by katrinagauci** [comment]
Yes :)

**Comment by ericforward** [comment]
@123betta This is our initial plant selection, what do you think about the cost? Perhaps before we order them we'd like to have a look in person. These are from Derek Garden Center, but i'm sure Piscopo have the same stuff, it's just their website was down.

[Plant Order.xlsx](https://github.com/Forward-architects/Forward-Office-Development/files/944357/Plant.Order.xlsx)

**Comment by ericforward** [comment]
hello

**Comment by ericforward** [comment]
@katrinagauci
